trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistry: 'mcCntRegistry Connection'
  containerImage: mccntregistry.azurecr.io/elm-lmp-api:$(Build.BuildId)
  testOutputDir: test-output

steps:
- task: Docker@2
  displayName: Login to Azure Container Registry
  inputs:
    command: login
    containerRegistry: $(azureContainerRegistry)
    repository: elm-lmp-api

- bash: bin/build
  displayName: Build container images
  env:
    CONTAINER_IMAGE: $(containerImage)

- bash: bin/test
  displayName: Test
  env:
    CONTAINER_IMAGE: $(containerImage)
    OUTPUT_DIR: $(testOutputDir)

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: $(testOutputDir)/TEST-*.xml
    failTaskOnFailedTests: true
    testRunTitle: Unit Test

- task: Docker@2
  displayName: Rebuild and push production container image
  inputs:
    command: buildandpush
    containerRegistry: $(azureContainerRegistry)
    repository: elm-lmp-web