trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: containergroup

steps:
- bash: mkdir test-output/ && chmod 777 test-output/
  displayName: Create test output folder

- task: DockerCompose@0
  displayName: Build container images
  inputs:
    action: Build services
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    dockerComposeFileArgs: |
      NODE_ENV=production
      PORT=3001
    qualifyImageNames: true

- task: DockerCompose@0
  displayName: Unit test
  inputs:
    action: Run a specific service
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    dockerComposeFileArgs: |
      NODE_ENV=production
      PORT=3001
    qualifyImageNames: true
    serviceName: unit-test
    detached: false

- task: PublishTestResults@2
  displayName: Publish unit test results
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: test-output/junit.xml
    failTaskOnFailedTests: true
    testRunTitle: Unit Test

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: test-output/cobertura-coverage.xml

- task: DockerCompose@0
  displayName: Push production images
  inputs:
    action: Push services
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    qualifyImageNames: true
