version: "3.4"

services:
  api:
    build:
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
      context: ./
      target: production

  unit-test:
    build:
      args:
        NODE_ENV: development
        PORT: ${PORT}
      context: ./
      target: development
    command: npm run test
    volumes:
      - "./test-output/:/home/node/test-output/"
