version: "3.4"

services:
  unit-test:
    build:
      args:
        NODE_ENV: development
        PORT: ${PORT}
      context: ../
      target: development
    command: npm run test
    volumes:
      - "../:/home/node/"
